# See the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase
    groups:
      gatsby:
        patterns:
          - "gatsby"
          - "gatsby-*"
      build-tooling:
        patterns:
          - "@pmmmwh/react-refresh-webpack-plugin"
          - "@typescript-eslint/*"
          - "@yarnpkg/*"
          - "eslint-*"
          - "eslint"
          - "netflify-cli"
          - "npm-run-all"
          - "postcss-*"
          - "postcss"
          - "prettier"
          - "sass"
          - "styelint"
          - "stylelint-*"
          - "typescript"
      blueprint:
        patterns:
          - "@blueprintjs/*"
      types:
        patterns:
          - "@types/*"
      react:
        patterns:
          - "react"
          - "react-*"
