logFilters:
  - pattern: "doesn't provide @babel/core"
    level: discard
  - pattern: "react is listed by your project with version 18.*.*, which doesn't satisfy what"
    level: discard
  - pattern: "react-dom is listed by your project with version 18.*.*, which doesn't satisfy what"
    level: discard
