version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/node:20.8

aliases:
  - &save-node-modules-cache
    name: Save node_modules cache
    paths:
      - node_modules
    key: yarn-packages-{{ checksum "yarn.lock" }}

  - &restore-node-modules-cache
    name: Restore node_modules cache
    key: yarn-packages-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    name: Save yarnpkg cache
    paths:
      - .yarn/cache
    key: yarn-cache-v1

  - &restore-yarn-cache
    name: Restore yarnpkg cache
    key: yarn-cache-v1

jobs:
  checkout-code:
    executor: default-executor
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - restore_cache: *restore-node-modules-cache
      - run: sudo corepack enable
      - run: yarn
      - run:
          name: Check if lockfile changed during install
          command: git diff --exit-code
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache

  build:
    executor: default-executor
    resource_class: large
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: sudo corepack enable
      - run: yarn build
      - persist_to_workspace:
          root: "."
          paths:
            - public

  check:
    executor: default-executor
    parallelism: 3
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: sudo corepack enable
      - run:
          command: |
            case $CIRCLE_NODE_INDEX in \
            0) yarn check:types ;; \
            1) yarn check:lint ;; \
            2) yarn check:format ;; \
            esac
          when: always

workflows:
  build_check:
    jobs:
      - checkout-code
      - build:
          requires: [checkout-code]
      - check:
          requires: [checkout-code]
