version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/node:24.21.0

aliases:
  - &save-yarn-cache
    name: Save Yarn Berry cache
    paths:
      - ~/.yarn/berry/cache
    key: yarn-berry-cache-v2-{{ checksum "yarn.lock" }}

  - &restore-yarn-cache
    name: Restore Yarn Berry cache
    key: yarn-berry-cache-v2-{{ checksum "yarn.lock" }}

jobs:
  checkout-code:
    executor: default-executor
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: sudo corepack enable
      - run: yarn install --immutable
      - run:
          name: Check if lockfile changed during install
          command: git diff --exit-code
      - save_cache: *save-yarn-cache

  build:
    executor: default-executor
    resource_class: large
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: sudo corepack enable
      - run: yarn install --immutable
      - run: yarn dist
      - run: yarn test:smoke

  check:
    executor: default-executor
    parallelism: 3
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: sudo corepack enable
      - run: yarn install --immutable
      - run:
          command: |
            case $CIRCLE_NODE_INDEX in \
            0) yarn check:types ;; \
            1) yarn check:lint ;; \
            2) yarn check:format ;; \
            esac
          when: always

workflows:
  build_check:
    jobs:
      - checkout-code
      - build:
          requires: [checkout-code]
      - check:
          requires: [checkout-code]
